/**
 * Phase 29: AI Project Generator.
 * Generates a bounded project specification into the mounted /workspace and can
 * hand the result to the existing AIWorkspaceBuilder. No host path is accepted.
 */
import type { ProotContainerManager } from "../container/ProotContainerManager";
import { AIWorkspaceBuilder, type WorkspaceBuildPlan, type WorkspaceBuildResult, type WorkspaceBuildTemplate } from "./AIWorkspaceBuilder";

export type GeneratedFile = { readonly path: string; readonly content: string };
export type AIProjectRequest = {
  readonly name: string;
  readonly goal: string;
  readonly template: WorkspaceBuildTemplate;
  readonly files?: readonly GeneratedFile[];
  readonly runWorkflow?: boolean;
  readonly build?: boolean;
  readonly test?: boolean;
};
export type AIProjectResult = {
  readonly ok: boolean;
  readonly name: string;
  readonly template: WorkspaceBuildTemplate;
  readonly goal: string;
  readonly files: readonly string[];
  readonly build?: WorkspaceBuildResult;
  readonly error?: string;
};

const MAX_FILES = 64;
const MAX_FILE_BYTES = 128 * 1024;
const MAX_TOTAL_BYTES = 2 * 1024 * 1024;
const NAME_RE = /^[a-zA-Z0-9][a-zA-Z0-9._-]{0,63}$/;

function safeRelativePath(value: string): string {
  const normalized = value.replace(/\\/g, "/").replace(/^\/+/, "");
  if (!normalized || normalized.includes("\0") || normalized.split("/").some((part) => part === ".." || part === "")) {
    throw new Error("PROJECT_FILE_PATH_INVALID");
  }
  if (normalized.length > 240) throw new Error("PROJECT_FILE_PATH_TOO_LONG");
  return normalized;
}

function bytes(value: string): number { return new TextEncoder().encode(value).byteLength; }

function isProtectedPath(path: string): boolean {
  const first = path.split("/")[0].toLowerCase();
  return first === ".git" || first === ".aib-snapshots" || first === ".aib-memory" ||
    path === ".env" || path.startsWith(".env.") ||
    /(^|\/)(?:.*(?:secret|credential|private)[^\/]*)\.(?:pem|key|p12|jks)$/i.test(path) ||
    /(^|\/)local\.properties$/i.test(path);
}

function templateFiles(request: AIProjectRequest): GeneratedFile[] {
  const common: GeneratedFile[] = [
    { path: "README.md", content: `# ${request.name}\n\nGoal: ${request.goal.trim()}\n\nGenerated by AI Builder Phase 29.\n` },
    { path: ".aib-project.json", content: JSON.stringify({ schema: 1, name: request.name, template: request.template, goal: request.goal }, null, 2) + "\n" },
  ];
  if (request.template === "node") {
    common.push(
      { path: "package.json", content: JSON.stringify({ name: request.name.toLowerCase().replace(/[^a-z0-9._-]/g, "-"), version: "0.1.0", private: true, scripts: { build: "node -e 'console.log(\"build ok\")'", test: "node -e 'console.log(\"test ok\")'" } }, null, 2) + "\n" },
      { path: "src/index.js", content: "export function main() { return { ok: true }; }\n" },
    );
  } else if (request.template === "expo") {
    common.push(
      { path: "package.json", content: JSON.stringify({ name: request.name.toLowerCase().replace(/[^a-z0-9._-]/g, "-"), version: "0.1.0", private: true, scripts: { build: "node -e 'console.log(\"expo workspace check ok\")'", test: "node -e 'console.log(\"test ok\")'" }, dependencies: { expo: "~54.0.29", react: "19.1.0", "react-native": "0.81.5" } }, null, 2) + "\n" },
      { path: "app.json", content: JSON.stringify({ expo: { name: request.name, slug: request.name.toLowerCase().replace(/[^a-z0-9-]/g, "-"), version: "0.1.0" } }, null, 2) + "\n" },
      { path: "App.js", content: "import { Text, View } from 'react-native';\nexport default function App() { return <View><Text>AI Builder project</Text></View>; }\n" },
    );
  } else {
    common.push(
      { path: "requirements.txt", content: "pytest>=8\n" },
      { path: "main.py", content: "def main():\n    return {'ok': True}\n\nif __name__ == '__main__':\n    print(main())\n" },
      { path: "tests/test_main.py", content: "from main import main\n\ndef test_main():\n    assert main()['ok'] is True\n" },
    );
  }
  return common;
}

export class AIProjectGenerator {
  constructor(private readonly containers: ProotContainerManager, private readonly workspaceBuilder: AIWorkspaceBuilder) {}

  async generate(containerId: string, request: AIProjectRequest): Promise<AIProjectResult> {
    if (!NAME_RE.test(request.name.trim())) throw new Error("PROJECT_NAME_INVALID");
    if (!request.goal.trim()) throw new Error("PROJECT_GOAL_REQUIRED");
    const files = [...templateFiles(request), ...(request.files ?? [])];
    if (files.length > MAX_FILES) throw new Error("PROJECT_FILE_LIMIT_EXCEEDED");
    const seen = new Set<string>();
    let total = 0;
    const normalized: GeneratedFile[] = [];
    for (const file of files) {
      const path = safeRelativePath(file.path);
      if (isProtectedPath(path)) throw new Error(`PROJECT_PROTECTED_PATH: ${path}`);
      if (seen.has(path)) throw new Error(`PROJECT_FILE_DUPLICATE: ${path}`);
      seen.add(path);
      const size = bytes(file.content);
      if (size > MAX_FILE_BYTES) throw new Error(`PROJECT_FILE_TOO_LARGE: ${path}`);
      total += size;
      if (total > MAX_TOTAL_BYTES) throw new Error("PROJECT_TOTAL_SIZE_LIMIT_EXCEEDED");
      normalized.push({ path, content: file.content });
    }

    for (const file of normalized) {
      const result = await this.writeFile(containerId, file.path, file.content);
      if (result.ok === false) return { ok: false, name: request.name, template: request.template, goal: request.goal, files: normalized.map((x) => x.path), error: result.error };
    }

    let build: WorkspaceBuildResult | undefined;
    if (request.runWorkflow !== false) {
      const plan: WorkspaceBuildPlan = { template: request.template, install: true, build: request.build !== false, test: request.test !== false, timeoutMs: 15 * 60_000 };
      build = await this.workspaceBuilder.run(containerId, plan);
    }
    return { ok: build ? build.ok : true, name: request.name, template: request.template, goal: request.goal, files: normalized.map((x) => x.path), build };
  }

  private async writeFile(containerId: string, relativePath: string, content: string): Promise<{ ok: true } | { ok: false; error: string }> {
    const escaped = JSON.stringify(content);
    const write = await this.containers.exec(containerId, "python3", ["-c", `import os; p=${JSON.stringify(`/workspace/${relativePath}`)}; os.makedirs(os.path.dirname(p),exist_ok=True); open(p,'w',encoding='utf-8').write(${escaped})`], { cwd: "/workspace", timeoutMs: 30_000 });
    if (write.exitCode !== 0) return { ok: false, error: write.stderr || `write failed: ${relativePath}` };
    return { ok: true };
  }
}

export function createAIProjectGenerator(containers: ProotContainerManager, workspaceBuilder: AIWorkspaceBuilder): AIProjectGenerator {
  return new AIProjectGenerator(containers, workspaceBuilder);
}
